<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

/**
 * Placeholder: Seeds password reset entries (normally generated by auth flows).
 */
class PasswordResetSeeder extends Seeder
{
    public function run(): void
    {
        // Not recommended to seed in production-like environments.
    }
}
